export const ALL_ADDRESS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/address/list`,
    REQUEST: 'REQUEST_ALL_ADDRESS_DATA',
    RECEIVED: 'RECEIVED_ALL_ADDRESS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ALL_ADDRESS_ERROR',
});

export const ADD_ADDRESS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/address`,
    REQUEST: 'REQUEST_ADD_ADDRESS_DATA',
    RECEIVED: 'RECEIVED_ADD_ADDRESS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ADD_ADDRESS_ERROR',
});

export const DELETE_ADDRESS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/address`,
    REQUEST: 'REQUEST_DELETE_ADDRESS_DATA',
    RECEIVED: 'RECEIVED_DELETE_ADDRESS_DATA',
    RECEIVED_ERROR: 'RECEIVED_DELETE_ADDRESS_ERROR',
});

export const EDIT_ADDRESS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/address`,
    // URL: 'http://localhost:2001/admin-bff/info/address',
    REQUEST: 'REQUEST_EDIT_ADDRESS_DATA',
    RECEIVED: 'RECEIVED_EDIT_ADDRESS_DATA',
    RECEIVED_ERROR: 'RECEIVED_EDIT_ADDRESS_ERROR',
});

export const SET_ADDR_ID_CONSTANTS = 'SET_ADDR_ID';
