

//export const FETCH_SHOP_HC = 'FETCH_SHOP_HC';

export const REQUEST_ONLINE_SALES_MAIN = 'REQUEST_ONLINE_SALES_MAIN';
export const RECEIVED_ONLINE_SALES_MAIN = 'RECEIVED_ONLINE_SALES_MAIN';
export const RECEIVED_ONLINE_SALES_MAIN_ERROR = 'RECEIVED_ONLINE_SALES_MAIN_ERROR';

export const REQUEST_ONLINE_SALES_SUB = 'REQUEST_ONLINE_SALES_SUB';
export const RECEIVED_ONLINE_SALES_SUB = 'RECEIVED_ONLINE_SALES_SUB';
export const RECEIVED_ONLINE_SALES_SUB_ERROR = 'RECEIVED_ONLINE_SALES_SUB_ERROR';

export const REQUEST_SHOP_HC_DETAIL = 'REQUEST_SHOP_HC_DETAIL';
export const RECEIVED_SHOP_HC_DETAIL = 'RECEIVED_SHOP_HC_DETAIL';
export const RECEIVED_SHOP_HC_ERROR = 'RECEIVED_SHOP_HC_ERROR';


export const REQUEST_EXPLORE_DETAIL = 'REQUEST_EXPLORE_DETAIL';
export const RECEIVED_EXPLORE_DETAIL = 'RECEIVED_EXPLORE_DETAIL';
export const RECEIVED_EXPLORE_DETAIL_ERROR = 'RECEIVED_EXPLORE_DETAIL_ERROR';


export const REQUEST_GENERIC_MEDICINE_DETAIL = 'REQUEST_GENERIC_MEDICINE_DETAIL';
export const RECEIVED_GENERIC_MEDICINE_DETAIL = 'RECEIVED_GENERIC_MEDICINE_DETAIL';
export const RECEIVED_GENERIC_MEDICINE_ERROR = 'RECEIVED_GENERIC_MEDICINE_ERROR';


export const RECEIVED_REVIEW_POST_SUBMIT_DETAIL = 'RECEIVED_REVIEW_POST_SUBMIT_DETAIL';
export const RECEIVED_REVIEW_POST_SUBMIT_ERROR = 'RECEIVED_REVIEW_POST_SUBMIT_ERROR';


export const REQUEST_FEATURED_BRAND_DETAIL = 'REQUEST_FEATURED_BRAND_DETAIL';
export const RECEIVED_FEATURED_BRAND_DETAIL = 'RECEIVED_FEATURED_BRAND_DETAIL';
export const RECEIVED_FEATURED_BRAND_ERROR = 'RECEIVED_FEATURED_BRAND_ERROR';


export const REQUEST_TOP_BRAND_DETAIL = 'REQUEST_TOP_BRAND_DETAIL';
export const RECEIVED_TOP_BRAND_DETAIL = 'RECEIVED_TOP_BRAND_DETAIL';
export const RECEIVED_TOP_BRAND_ERROR = 'RECEIVED_TOP_BRAND_ERROR';