
export const REQUEST_EMERGENCY_HEALTH = 'REQUEST_EMERGENCY_HEALTH';
export const RECEIVED_EMERGENCY_HEALTH = 'RECEIVED_EMERGENCY_HEALTH';
export const RECEIVED_EMERGENCY_HEALTH_ERROR = 'RECEIVED_EMERGENCY_HEALTH_ERROR';


export const REQUEST_GC_TESTIMONIALS = 'REQUEST_GC_TESTIMONIALS';
export const RECEIVED_GC_TESTIMONIALS = 'RECEIVED_GC_TESTIMONIALS';
export const RECEIVED_GC_TESTIMONIALS_ERROR = 'RECEIVED_GC_TESTIMONIALS_ERROR';


export const REQUEST_ELDERLY_CARE = 'REQUEST_ELDERLY_CARE';
export const RECEIVED_ELDERLY_CARE = 'RECEIVED_ELDERLY_CARE';
export const RECEIVED_ELDERLY_CARE_ERROR = 'RECEIVED_ELDERLY_CARE_ERROR';
