
export const REQUEST_LAB_TESTIMONIALS = 'REQUEST_LAB_TESTIMONIALS';
export const RECEIVED_LAB_TESTIMONIALS = 'RECEIVED_LAB_TESTIMONIALS';
export const RECEIVED_LAB_TESTIMONIALS_ERROR = 'RECEIVED_LAB_TESTIMONIALS_ERROR';


export const REQUEST_LAB_SHC = 'REQUEST_LAB_SHC';
export const RECEIVED_LAB_SHC = 'RECEIVED_LAB_SHC';
export const RECEIVED_LAB_SHC_ERROR = 'RECEIVED_LAB_SHC_ERROR';
