export const LOGIN_URL = `${process.env.APPLICATION_BFF_URL}/user/login`;

export const REQUEST_LOGIN_DATA = 'REQUEST_LOGIN_DATA';
export const RECEIVED_LOGIN_DATA = 'RECEIVED_LOGIN_DATA';
export const RECEIVED_LOGIN_ERROR = 'RECEIVED_LOGIN_ERROR';

export const FORGOT_PASSWORD_URL = `${process.env.APPLICATION_BFF_URL}/user/forgot`;

export const REQUEST_FORGOT_PASSWORD_DATA = 'REQUEST_FORGOT_PASSWORD_DATA';
export const RECEIVED_FORGOT_PASSWORD_DATA = 'RECEIVED_FORGOT_PASSWORD_DATA';
export const RECEIVED_FORGOT_PASSWORD_ERROR = 'RECEIVED_FORGOT_PASSWORD_ERROR';

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const CLEAR_SALES_REP_FLAG = 'CLEAR_SALES_REP_FLAG';

export const SET_ZIPCODE = 'SET_ZIPCODE';

export const SET_STORE_ID = 'SET_STORE_ID';

export const SET_CART_ID = 'SET_CART_ID';

export const FLUSH_CART_DATA = 'FLUSH_CART_DATA';

export const UPDATE_CART = 'UPDATE_CART';

export const RESET_FORGOT_PASSWORD_DATA = 'RESET_FORGOT_PASSWORD_DATA';

export const NEWSLETTER_SUBSCRIPTION_DATA = 'NEWSLETTER_SUBSCRIPTION_DATA';
/* for getting profile data */

export const PROFILE_DATA_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/account`,
    REQUEST: 'REQUEST_PROFILE_DATA',
    RECEIVED: 'RECEIVED_PROFILE_DATA',
    RECEIVED_ERROR: 'REQUEST_PROFILE_DATA_ERROR',
});

export const CATEGORIES_LIST_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/categories/list`,
    REQUEST: 'REQUEST_CATEGORIES_LIST',
    RECEIVED: 'RECEIVED_CATEGORIES_LIST',
    RECEIVED_ERROR: 'REQUEST_CATEGORIES_LIST_ERROR',
});

export const NEWSLETTER_SUBSCRIPTION_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/newsLetter/subscription`,
    REQUEST: 'REQUEST_NEWSLETTER_SUBSCRIPTION',
    RECEIVED: 'RECEIVED_NEWSLETTER_SUBSCRIPTION',
    RECEIVED_ERROR: 'REQUEST_NEWSLETTER_SUBSCRIPTION_ERROR',
});

export const USER_LOGOUT_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/user/logout`,
    REQUEST: 'REQUEST_USER_LOGOUT',
    RECEIVED: 'RECEIVED_USER_LOGOUT',
    RECEIVED_ERROR: 'REQUEST_USER_LOGOUT_ERROR',
});

export const UPDATE_PRIME_ID = 'UPDATE_PRIME_ID';

export const ARTIST_EMAIL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/email/`,
    REQUEST: 'REQUEST_ARTIST_EMAIL_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_EMAIL_CONSTANTS',
    RECEIVED_ERROR: 'REQUEST_ARTIST_EMAIL_CONSTANTS_ERROR',
});
