export const PRODUCTS_DETAIL_URL = `${process.env.APPLICATION_BFF_URL}/product/detail`;

export const REQUEST_PRODUCT_DETAIL = 'REQUEST_PRODUCT_DETAIL';
export const RECEIVED_PRODUCT_DETAIL = 'RECEIVED_PRODUCT_DETAIL';
export const RECEIVED_PRODUCT_DETAIL_ERROR = 'RECEIVED_PRODUCT_DETAIL_ERROR';

export const RELATED_PRODUCTS_URL = `${process.env.APPLICATION_BFF_URL}/product/related`;

export const REQUEST_RELATED_PRODUCT = 'REQUEST_RELATED_PRODUCT';
export const RECEIVED_RELATED_PRODUCT = 'RECEIVED_RELATED_PRODUCT';
export const RECEIVED_RELATED_PRODUCT_ERROR = 'RECEIVED_RELATED_PRODUCT_ERROR';

export const ADD_PRODUCT_TAGS_URL = `${process.env.APPLICATION_BFF_URL}/product/tags`;

export const REQUEST_ADD_PRODUCT_TAGS = 'REQUEST_ADD_PRODUCT_TAGS';
export const RECEIVED_ADD_PRODUCT_TAGS = 'RECEIVED_ADD_PRODUCT_TAGS';
export const RECEIVED_ADD_PRODUCT_TAGS_ERROR = 'RECEIVED_ADD_PRODUCT_TAGS_ERROR';

export const PRODUCT_REVIEWS_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/products/reviews`,
    REQUEST: 'REQUEST_SUBMIT_REVIEWS',
    RECEIVED: 'RECEIVED_SUBMIT_REVIEWS',
    RECEIVED_ERROR: 'RECEIVED_SUBMIT_REVIEWS_ERROR',
});

export const UPSELL_PRODUCTS_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/upsell`,
    REQUEST: 'REQUEST_UPSELL_PRODUCTS',
    RECEIVED: 'RECEIVED_UPSELL_PRODUCTS',
    RECEIVED_ERROR: 'RECEIVED_UPSELL_PRODUCTS_ERROR',
});

export const PRODUCT_REVIEWS_LIST_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/products/reviews`,
    REQUEST: 'REQUEST_LIST_REVIEWS',
    RECEIVED: 'RECEIVED_LIST_REVIEWS',
    RECEIVED_ERROR: 'RECEIVED_LIST_REVIEWS_ERROR',
});

export const HOVER_PRODUCT_REVIEWS_LIST_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/products/reviews`,
    REQUEST: 'REQUEST_HOVER_LIST_REVIEWS',
    RECEIVED: 'RECEIVED_HOVER_LIST_REVIEWS',
    RECEIVED_ERROR: 'RECEIVED_HOVER_LIST_REVIEWS_ERROR',
});

export const PRODUCT_TAGS_LIST_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/products/tags`,
    REQUEST: 'REQUEST_LIST_TAGS',
    RECEIVED: 'RECEIVED_LIST_TAGS',
    RECEIVED_ERROR: 'RECEIVED_LIST_TAGS_ERROR',
});

export const PRODUCT_TAG_DETAILS_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/products/tags`,
    REQUEST: 'REQUEST_TAG_DETAILS',
    RECEIVED: 'RECEIVED_TAG_DETAILS',
    RECEIVED_ERROR: 'RECEIVED_TAG_DETAILS_ERROR',
});

export const REMOVE_TAG_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/products/tags`,
    REQUEST: 'REQUEST_TAG_DELETE',
    RECEIVED: 'RECEIVED_TAG_DELETE',
    RECEIVED_ERROR: 'RECEIVED_TAG_DELETE_ERROR',
});
