export const ARTIST_VENDOR_LOGIN_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/email/`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_LOGIN_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_LOGIN_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_VENDOR_LOGIN_CONSTANTS_ERROR',
});


export const ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/vendor/product/upload`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS_ERROR',
});

export const ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/po/management`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS_ERROR',
});

export const ARTIST_PRODUCT_UPLOAD_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/creation`,
    REQUEST: 'REQUEST_PRODUCT_UPLOAD_CONSTANTS',
    RECEIVED: 'RECEIVED_PRODUCT_UPLOAD_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_PRODUCT_UPLOAD_CONSTANTS_ERROR',
});

export const ARTIST_PRODUCTS_LIST_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/productsByArtist`,
    REQUEST: 'REQUEST_ARTIST_PRODUCTS_LIST_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_PRODUCTS_LIST_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_PRODUCTS_LIST_CONSTANTS_ERROR',
});

export const ARTIST_LOGISTIC_SETTINGS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/logisticDetails`,
    REQUEST: 'REQUEST_ARTIST_LOGISTIC_SETTINGS_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_ERROR',
});

export const ARTIST_UPDATE_LOGISTIC_SETTINGS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/logisticDetails/update`,
    REQUEST: 'REQUEST_UPDATE_ARTIST_LOGISTIC_SETTINGS_CONSTANTS',
    RECEIVED: 'RECEIVED_UPDATE_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_UPDATE_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_ERROR',
});
