export const ARTIST_VENDOR_LOGIN_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/email/`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_LOGIN_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_LOGIN_CONSTANTS',
    RECEIVED_ERROR: 'REQUEST_ARTIST_VENDOR_LOGIN_CONSTANTSs',
});


export const ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/vendor/product/upload`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS',
    RECEIVED_ERROR: 'REQUEST_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS',
});
